import type {
  MemoryItem,
  CreateMemoryPayload,
  UpdateMemoryPayload,
} from "../marketing-memory.types";

const delay = (ms = 400) => new Promise<void>((r) => setTimeout(r, ms));

let _nextId = 101;
const nextId = () => _nextId++;

let mockMemories: MemoryItem[] = [
  {
    id: 1,
    title: "Летний фестиваль 2026",
    description:
      "Грандиозный летний фестиваль с живой музыкой, аттракционами и выступлениями артистов.",
    category: "events",
    date: "2026-07-07",
    photo_count: 42,
    like_count: 318,
    view_count: 2140,
    thumbnail: null,
  },
  {
    id: 2,
    title: "Детский день — счастливые лица",
    description:
      "В детский день парк наполнился смехом и радостью. Дети до 5 лет проходили бесплатно.",
    category: "guests",
    date: "2026-07-06",
    photo_count: 63,
    like_count: 487,
    view_count: 3820,
    thumbnail: null,
  },
  {
    id: 3,
    title: "Утро в парке — рассвет над прудом",
    description:
      "Серия фотографий ранним утром, когда парк ещё пустой. Туман над водой и первые лучи.",
    category: "nature",
    date: "2026-07-05",
    photo_count: 27,
    like_count: 204,
    view_count: 1590,
    thumbnail: null,
  },
  {
    id: 4,
    title: "Открытие аттракциона «Гравитон»",
    description:
      "Торжественное открытие нового аттракциона. Первые посетители получили подарки.",
    category: "events",
    date: "2026-07-04",
    photo_count: 18,
    like_count: 142,
    view_count: 980,
    thumbnail: null,
  },
  {
    id: 5,
    title: "Кинопоказ под звёздами",
    description:
      "Ночной кинопоказ классики под открытым небом. Зрители взяли пледы и попкорн.",
    category: "events",
    date: "2026-07-04",
    photo_count: 31,
    like_count: 276,
    view_count: 1870,
    thumbnail: null,
  },
  {
    id: 6,
    title: "День рождения парка — 11 лет",
    description:
      "Юбилейный день рождения парка. Торт, воздушные шары и поздравления партнёров.",
    category: "guests",
    date: "2026-07-04",
    photo_count: 91,
    like_count: 654,
    view_count: 5130,
    thumbnail: null,
  },
  {
    id: 7,
    title: "Прогулка по парку — воскресенье",
    description:
      "Фотопрогулка по аллеям парка. Уютные дорожки и яркие летние краски.",
    category: "nature",
    date: "2026-06-29",
    photo_count: 34,
    like_count: 198,
    view_count: 1240,
    thumbnail: null,
  },
  {
    id: 8,
    title: "Концерт под открытым небом",
    description:
      "Живая музыка у главной сцены. Три группы, тысячи зрителей, незабываемая атмосфера.",
    category: "events",
    date: "2026-06-28",
    photo_count: 57,
    like_count: 412,
    view_count: 3100,
    thumbnail: null,
  },
  {
    id: 9,
    title: "Пасхальный праздник",
    description:
      "Пасхальные гуляния с конкурсом по раскрашиванию яиц и угощениями для детей.",
    category: "events",
    date: "2026-06-27",
    photo_count: 45,
    like_count: 335,
    view_count: 2350,
    thumbnail: null,
  },
  {
    id: 10,
    title: "Школьная экскурсия — 4А класс",
    description:
      "Учащиеся 4А класса посетили парк всем составом. Дети в восторге от аттракционов.",
    category: "guests",
    date: "2026-06-26",
    photo_count: 22,
    like_count: 167,
    view_count: 890,
    thumbnail: null,
  },
  {
    id: 11,
    title: "Фестиваль воздушных змеев",
    description:
      "Ежегодный фестиваль воздушных змеев. Небо над парком было полно ярких красок.",
    category: "events",
    date: "2026-06-22",
    photo_count: 78,
    like_count: 521,
    view_count: 3780,
    thumbnail: null,
  },
  {
    id: 12,
    title: "Закат над каруселями",
    description:
      "Золотой час на аттракционах. Силуэты каруселей на фоне вечернего неба.",
    category: "nature",
    date: "2026-06-21",
    photo_count: 19,
    like_count: 389,
    view_count: 2940,
    thumbnail: null,
  },
  {
    id: 13,
    title: "День семьи — фото со всем парком",
    description:
      "День семьи: тысячи пар и семей собрались в парке на праздник единства.",
    category: "guests",
    date: "2026-06-15",
    photo_count: 104,
    like_count: 743,
    view_count: 4690,
    thumbnail: null,
  },
  {
    id: 14,
    title: "Мастер-класс по рисованию",
    description:
      "Художники провели открытый мастер-класс для детей прямо в центре парка.",
    category: "events",
    date: "2026-06-14",
    photo_count: 36,
    like_count: 213,
    view_count: 1420,
    thumbnail: null,
  },
  {
    id: 15,
    title: "Пруд с утками — утренние кадры",
    description: "Утки вернулись в пруд. Ранние посетители кормят птиц у воды.",
    category: "nature",
    date: "2026-06-13",
    photo_count: 24,
    like_count: 178,
    view_count: 1100,
    thumbnail: null,
  },
  {
    id: 16,
    title: "Корпоратив «АгроИнвест»",
    description:
      "Компания арендовала зону пикника. Команда из 80 человек провела тимбилдинг.",
    category: "guests",
    date: "2026-06-12",
    photo_count: 29,
    like_count: 145,
    view_count: 780,
    thumbnail: null,
  },
  {
    id: 17,
    title: "Турнир по пейнтболу",
    description:
      "Восемь команд сразились за кубок парка. Победила команда «Красные лисы».",
    category: "events",
    date: "2026-06-08",
    photo_count: 53,
    like_count: 298,
    view_count: 2010,
    thumbnail: null,
  },
  {
    id: 18,
    title: "Посадка деревьев — экоакция",
    description:
      "Волонтёры и сотрудники парка высадили 200 новых деревьев по периметру.",
    category: "other",
    date: "2026-06-07",
    photo_count: 17,
    like_count: 132,
    view_count: 670,
    thumbnail: null,
  },
  {
    id: 19,
    title: "Молодожёны на аллее роз",
    description:
      "Свадебная фотосессия в парке. Пара выбрала аллею роз для памятных снимков.",
    category: "guests",
    date: "2026-06-06",
    photo_count: 61,
    like_count: 592,
    view_count: 4120,
    thumbnail: null,
  },
  {
    id: 20,
    title: "Спортивный марафон 5 км",
    description:
      "Ежегодный марафон вдоль аллей парка. 350 участников, все финишировали.",
    category: "events",
    date: "2026-06-01",
    photo_count: 88,
    like_count: 467,
    view_count: 3340,
    thumbnail: null,
  },
  {
    id: 21,
    title: "Открытие летнего сезона",
    description:
      "Торжественное открытие сезона 2026. Первый день работы всех новых аттракционов.",
    category: "events",
    date: "2026-05-30",
    photo_count: 112,
    like_count: 815,
    view_count: 6200,
    thumbnail: null,
  },
  {
    id: 22,
    title: "Цветочные клумбы мая",
    description:
      "Парковые садоводы высадили 15 000 цветков. Клумбы в полном цвету.",
    category: "nature",
    date: "2026-05-28",
    photo_count: 41,
    like_count: 356,
    view_count: 2580,
    thumbnail: null,
  },
  {
    id: 23,
    title: "День защиты детей",
    description:
      "1 июня — день детей. Бесплатные билеты, конкурсы, мороженое и шарики.",
    category: "events",
    date: "2026-05-25",
    photo_count: 95,
    like_count: 681,
    view_count: 4870,
    thumbnail: null,
  },
  {
    id: 24,
    title: "Группа из детского сада №12",
    description:
      "Малыши 4–5 лет впервые посетили парк. Восторг и удивление на каждом шагу.",
    category: "guests",
    date: "2026-05-22",
    photo_count: 38,
    like_count: 294,
    view_count: 2010,
    thumbnail: null,
  },
  {
    id: 25,
    title: "Весенний цвет деревьев",
    description:
      "Парк в цвету. Сакуры, каштаны и яблони одновременно зацвели в один день.",
    category: "nature",
    date: "2026-05-18",
    photo_count: 67,
    like_count: 502,
    view_count: 3600,
    thumbnail: null,
  },
  {
    id: 26,
    title: "Иностранные туристы — группа из KR",
    description:
      "Делегация туристов из Кореи. Парк попал в корейский тревел-блог.",
    category: "guests",
    date: "2026-05-16",
    photo_count: 33,
    like_count: 228,
    view_count: 1540,
    thumbnail: null,
  },
  {
    id: 27,
    title: "Реставрация главного фонтана",
    description:
      "Фонтан отреставрировали после зимы. Первое включение под аплодисменты гостей.",
    category: "other",
    date: "2026-05-12",
    photo_count: 21,
    like_count: 189,
    view_count: 1080,
    thumbnail: null,
  },
  {
    id: 28,
    title: "Ночные огни парка",
    description:
      "Тестирование новой LED-подсветки аллей и аттракционов в ночном режиме.",
    category: "nature",
    date: "2026-05-10",
    photo_count: 73,
    like_count: 634,
    view_count: 4450,
    thumbnail: null,
  },
  {
    id: 29,
    title: "Открытие кафе «Лесная поляна»",
    description:
      "Новое летнее кафе открылось у пруда. Деревянный декор и живая зелень.",
    category: "other",
    date: "2026-05-08",
    photo_count: 26,
    like_count: 214,
    view_count: 1390,
    thumbnail: null,
  },
  {
    id: 30,
    title: "Масленица в парке",
    description:
      "Сжигание чучела, блины и народные гуляния. Парк собрал 4 000 посетителей.",
    category: "events",
    date: "2026-05-05",
    photo_count: 86,
    like_count: 573,
    view_count: 4010,
    thumbnail: null,
  },
  {
    id: 31,
    title: "Пенсионеры на прогулке — среда",
    description:
      "Каждую среду старшее поколение приходит бесплатно. Уют и спокойствие.",
    category: "guests",
    date: "2026-05-04",
    photo_count: 14,
    like_count: 97,
    view_count: 610,
    thumbnail: null,
  },
  {
    id: 32,
    title: "Радуга над парком",
    description:
      "После летнего ливня над парком появилась двойная радуга. Редкий кадр.",
    category: "nature",
    date: "2026-04-29",
    photo_count: 9,
    like_count: 721,
    view_count: 5380,
    thumbnail: null,
  },
  {
    id: 33,
    title: "Мастер-класс по лепке из глины",
    description:
      "Детская мастерская под открытым небом. Более 60 детей слепили фигурки.",
    category: "events",
    date: "2026-04-26",
    photo_count: 32,
    like_count: 201,
    view_count: 1260,
    thumbnail: null,
  },
  {
    id: 34,
    title: "Фото-сессия с персонажами",
    description:
      "Аниматоры в костюмах мультяшных героев устроили флешмоб у входа.",
    category: "events",
    date: "2026-04-20",
    photo_count: 55,
    like_count: 389,
    view_count: 2720,
    thumbnail: null,
  },
  {
    id: 35,
    title: "Блогер Kamola снимает обзор",
    description:
      "Популярный блогер с 500k подписчиков провёл день в парке и снял рилс.",
    category: "guests",
    date: "2026-04-18",
    photo_count: 47,
    like_count: 917,
    view_count: 7840,
    thumbnail: null,
  },
  {
    id: 36,
    title: "Новые скамейки — установка",
    description:
      "По всему парку установлено 40 новых деревянных скамеек с гравировкой.",
    category: "other",
    date: "2026-04-15",
    photo_count: 12,
    like_count: 88,
    view_count: 510,
    thumbnail: null,
  },
  {
    id: 37,
    title: "Летний ливень — кадры во время дождя",
    description:
      "Сильный дождь застал посетителей врасплох. Уникальные кадры под зонтами.",
    category: "nature",
    date: "2026-04-12",
    photo_count: 28,
    like_count: 315,
    view_count: 2200,
    thumbnail: null,
  },
  {
    id: 38,
    title: "Школьники на выпускном пикнике",
    description:
      "Выпускники 11-го класса провели прощальный пикник в парке перед экзаменами.",
    category: "guests",
    date: "2026-04-10",
    photo_count: 74,
    like_count: 461,
    view_count: 3180,
    thumbnail: null,
  },
  {
    id: 39,
    title: "Именинник получает торт у фонтана",
    description:
      "Постоянный гость отметил 30-летие в парке. Сюрприз от администрации.",
    category: "guests",
    date: "2026-04-08",
    photo_count: 16,
    like_count: 143,
    view_count: 870,
    thumbnail: null,
  },
  {
    id: 40,
    title: "День смеха — розыгрыши в парке",
    description:
      "1 апреля: аниматоры устроили весёлые розыгрыши у каждого аттракциона.",
    category: "events",
    date: "2026-04-01",
    photo_count: 49,
    like_count: 378,
    view_count: 2630,
    thumbnail: null,
  },
  {
    id: 41,
    title: "Весенняя уборка — волонтёры",
    description:
      "300 волонтёров вышли на субботник. Собрали 5 тонн мусора после зимы.",
    category: "other",
    date: "2026-03-28",
    photo_count: 39,
    like_count: 262,
    view_count: 1740,
    thumbnail: null,
  },
  {
    id: 42,
    title: "Аттракцион «Зеркальный лабиринт»",
    description:
      "Открытие нового аттракциона с зеркалами. Очередь выстроилась с утра.",
    category: "events",
    date: "2026-03-22",
    photo_count: 66,
    like_count: 498,
    view_count: 3560,
    thumbnail: null,
  },
  {
    id: 43,
    title: "Первые тюльпаны парка",
    description:
      "Первые тюльпаны распустились раньше срока. Фотографы не могли уйти.",
    category: "nature",
    date: "2026-03-18",
    photo_count: 52,
    like_count: 447,
    view_count: 3140,
    thumbnail: null,
  },
  {
    id: 44,
    title: "Международный день женщин",
    description:
      "8 марта — каждой женщине-посетительнице подарили тюльпан у входа.",
    category: "events",
    date: "2026-03-08",
    photo_count: 83,
    like_count: 612,
    view_count: 4380,
    thumbnail: null,
  },
  {
    id: 45,
    title: "Многодетная семья — 8 детей",
    description:
      "Семья с восемью детьми стала героем дня. Бесплатные билеты в знак уважения.",
    category: "guests",
    date: "2026-03-05",
    photo_count: 23,
    like_count: 534,
    view_count: 3920,
    thumbnail: null,
  },
  {
    id: 46,
    title: "Зимнее кафе у входа закрылось",
    description:
      "Сезонное зимнее кафе завершило работу. Благодарим за тёплый глинтвейн!",
    category: "other",
    date: "2026-03-01",
    photo_count: 11,
    like_count: 76,
    view_count: 430,
    thumbnail: null,
  },
  {
    id: 47,
    title: "Снегопад в парке — редкие кадры",
    description:
      "Неожиданный снегопад в конце февраля. Аттракционы в снегу выглядят волшебно.",
    category: "nature",
    date: "2026-02-25",
    photo_count: 58,
    like_count: 567,
    view_count: 4050,
    thumbnail: null,
  },
  {
    id: 48,
    title: "День всех влюблённых",
    description:
      "14 февраля: пары фотографировались у сердца из цветов у главного входа.",
    category: "events",
    date: "2026-02-14",
    photo_count: 99,
    like_count: 832,
    view_count: 6710,
    thumbnail: null,
  },
  {
    id: 49,
    title: "Новые указатели по всему парку",
    description:
      "Установлены современные двуязычные указатели на всех развилках парка.",
    category: "other",
    date: "2026-02-10",
    photo_count: 8,
    like_count: 64,
    view_count: 390,
    thumbnail: null,
  },
  {
    id: 50,
    title: "Корпоратив «ТехноГрупп» — 120 чел.",
    description:
      "Крупный корпоратив с квестом, BBQ и аттракционами. Компания в восторге.",
    category: "guests",
    date: "2026-02-07",
    photo_count: 71,
    like_count: 319,
    view_count: 2270,
    thumbnail: null,
  },
  {
    id: 51,
    title: "Зимний иллюминированный парк",
    description:
      "Февральская иллюминация: 50 000 огней украсили аллеи и деревья парка.",
    category: "nature",
    date: "2026-02-01",
    photo_count: 87,
    like_count: 769,
    view_count: 5940,
    thumbnail: null,
  },
  {
    id: 52,
    title: "Ледяные скульптуры у пруда",
    description:
      "Конкурс ледяных скульптур. Мастера вырезали 12 фигур из льда за 6 часов.",
    category: "events",
    date: "2026-01-28",
    photo_count: 64,
    like_count: 438,
    view_count: 3010,
    thumbnail: null,
  },
  {
    id: 53,
    title: "Старый Новый год — вечеринка",
    description:
      "Вечеринка по случаю Старого Нового года. Живая музыка и фейерверк.",
    category: "events",
    date: "2026-01-14",
    photo_count: 43,
    like_count: 307,
    view_count: 2140,
    thumbnail: null,
  },
  {
    id: 54,
    title: "Новогодняя ёлка 2026",
    description: "Главная ёлка парка высотой 12 метров зажглась под снегопад.",
    category: "events",
    date: "2026-01-01",
    photo_count: 116,
    like_count: 924,
    view_count: 7290,
    thumbnail: null,
  },
  {
    id: 55,
    title: "Рождественский базар",
    description:
      "Ярмарка у главного входа: мёд, поделки, ёлочные игрушки и глинтвейн.",
    category: "events",
    date: "2025-12-25",
    photo_count: 77,
    like_count: 556,
    view_count: 3890,
    thumbnail: null,
  },
  {
    id: 56,
    title: "Первый снег сезона 2025",
    description:
      "Ранний снег накрыл парк в ноябре. Посетители радовались как дети.",
    category: "nature",
    date: "2025-12-20",
    photo_count: 46,
    like_count: 412,
    view_count: 2960,
    thumbnail: null,
  },
  {
    id: 57,
    title: "Хэллоуин в парке",
    description:
      "Страшный праздник с тыквами, привидениями и пугающими аниматорами.",
    category: "events",
    date: "2025-12-14",
    photo_count: 92,
    like_count: 688,
    view_count: 4810,
    thumbnail: null,
  },
  {
    id: 58,
    title: "Осенний листопад — октябрь",
    description:
      "Парк в золотом убранстве. Тысячи фото, сотни счастливых посетителей.",
    category: "nature",
    date: "2025-12-08",
    photo_count: 60,
    like_count: 479,
    view_count: 3350,
    thumbnail: null,
  },
  {
    id: 59,
    title: "Ремонт освещения аллей",
    description:
      "Замена устаревших фонарей на LED. Экономия электроэнергии 40%.",
    category: "other",
    date: "2025-12-02",
    photo_count: 7,
    like_count: 49,
    view_count: 290,
    thumbnail: null,
  },
  {
    id: 60,
    title: "Последний день сезона аттракционов",
    description:
      "Закрытие летнего сезона. Последние посетители получили памятные браслеты.",
    category: "events",
    date: "2025-11-30",
    photo_count: 54,
    like_count: 398,
    view_count: 2750,
    thumbnail: null,
  },
  {
    id: 61,
    title: "День народного единства",
    description:
      "Парк стал площадкой для городских торжеств. Концерты и выставки.",
    category: "events",
    date: "2025-11-04",
    photo_count: 69,
    like_count: 461,
    view_count: 3240,
    thumbnail: null,
  },
  {
    id: 62,
    title: "Подготовка к зиме — консервация",
    description: "Работники укрыли клумбы и законсервировали фонтаны до весны.",
    category: "other",
    date: "2025-11-01",
    photo_count: 15,
    like_count: 98,
    view_count: 580,
    thumbnail: null,
  },
  {
    id: 63,
    title: "Уборка листьев — ежегодная акция",
    description: "500 волонтёров собрали листву по всему парку за один день.",
    category: "other",
    date: "2025-10-25",
    photo_count: 30,
    like_count: 213,
    view_count: 1420,
    thumbnail: null,
  },
  {
    id: 64,
    title: "Осенний квест для детей",
    description:
      "Квест «Сокровища осеннего парка» прошли 420 детей команды по 5 человек.",
    category: "events",
    date: "2025-10-19",
    photo_count: 48,
    like_count: 337,
    view_count: 2380,
    thumbnail: null,
  },
  {
    id: 65,
    title: "День пожилых людей",
    description:
      "Бесплатный день для посетителей старше 60. Живая музыка и чай.",
    category: "guests",
    date: "2025-10-12",
    photo_count: 25,
    like_count: 187,
    view_count: 1150,
    thumbnail: null,
  },
  {
    id: 66,
    title: "Фото в жёлтых аллеях",
    description:
      "Профессиональная съёмка для соцсетей парка в период золотой осени.",
    category: "nature",
    date: "2025-10-07",
    photo_count: 80,
    like_count: 623,
    view_count: 4390,
    thumbnail: null,
  },
  {
    id: 67,
    title: "Музыкальный пикник выходного дня",
    description:
      "Джазовый квартет выступил в беседке у пруда. 600 слушателей на траве.",
    category: "events",
    date: "2025-09-28",
    photo_count: 56,
    like_count: 402,
    view_count: 2830,
    thumbnail: null,
  },
  {
    id: 68,
    title: "Открытие велодорожки",
    description:
      "Новая велодорожка длиной 3 км прошла через весь парк. Первые велосипедисты.",
    category: "other",
    date: "2025-09-21",
    photo_count: 37,
    like_count: 276,
    view_count: 1890,
    thumbnail: null,
  },
  {
    id: 69,
    title: "День знаний в парке",
    description:
      "1 сентября: школьники с учителями провели первый день в парке.",
    category: "events",
    date: "2025-09-01",
    photo_count: 70,
    like_count: 514,
    view_count: 3670,
    thumbnail: null,
  },
  {
    id: 70,
    title: "Ночной забег по парку",
    description:
      "5 км в темноте с фонариками. 200 участников, все финишировали.",
    category: "events",
    date: "2025-08-30",
    photo_count: 44,
    like_count: 329,
    view_count: 2310,
    thumbnail: null,
  },
  {
    id: 71,
    title: "Фотовыставка под открытым небом",
    description:
      "30 фотографий на стендах вдоль аллеи. Выставка работала 2 недели.",
    category: "events",
    date: "2025-08-23",
    photo_count: 35,
    like_count: 254,
    view_count: 1730,
    thumbnail: null,
  },
  {
    id: 72,
    title: "День рождения аттракциона «Вихрь»",
    description:
      "Популярному аттракциону исполнилось 5 лет. Именинный торт и скидки.",
    category: "events",
    date: "2025-08-17",
    photo_count: 28,
    like_count: 198,
    view_count: 1310,
    thumbnail: null,
  },
  {
    id: 73,
    title: "Пикник с йогой на рассвете",
    description:
      "Утренняя йога-практика на большой поляне. 80 участников встретили рассвет.",
    category: "events",
    date: "2025-08-10",
    photo_count: 50,
    like_count: 367,
    view_count: 2510,
    thumbnail: null,
  },
  {
    id: 74,
    title: "Аквазона — открытие сезона",
    description:
      "Открытие водного сектора. Горки, бассейн и зоны отдыха заполнились гостями.",
    category: "events",
    date: "2025-08-03",
    photo_count: 97,
    like_count: 712,
    view_count: 5010,
    thumbnail: null,
  },
  {
    id: 75,
    title: "Туристы из Китая в парке",
    description:
      "Группа из 45 туристов из Шанхая. Парк упомянули в китайском туристическом гиде.",
    category: "guests",
    date: "2025-07-27",
    photo_count: 42,
    like_count: 286,
    view_count: 1980,
    thumbnail: null,
  },
  {
    id: 76,
    title: "Летний концерт поп-музыки",
    description:
      "Местные поп-исполнители выступили на большой сцене у входа в парк.",
    category: "events",
    date: "2025-07-20",
    photo_count: 81,
    like_count: 598,
    view_count: 4210,
    thumbnail: null,
  },
  {
    id: 77,
    title: "Семейный баскетбол на площадке",
    description:
      "Первый открытый турнир «семья vs семья». 16 команд, победители получили призы.",
    category: "events",
    date: "2025-07-14",
    photo_count: 33,
    like_count: 234,
    view_count: 1590,
    thumbnail: null,
  },
  {
    id: 78,
    title: "Покраска каруселей — лето 2025",
    description: "Ежегодное обслуживание и покраска 8 каруселей к пику сезона.",
    category: "other",
    date: "2025-07-07",
    photo_count: 19,
    like_count: 112,
    view_count: 720,
    thumbnail: null,
  },
  {
    id: 79,
    title: "Дети рисуют мелом на асфальте",
    description:
      "Фестиваль асфальтовых рисунков. Более 100 рисунков украсили центральную площадь.",
    category: "events",
    date: "2025-07-01",
    photo_count: 62,
    like_count: 431,
    view_count: 3020,
    thumbnail: null,
  },
  {
    id: 80,
    title: "Гостья-блогер из Москвы",
    description:
      "Тревел-блогер с 1.2M подписчиков провела день и опубликовала пост.",
    category: "guests",
    date: "2025-06-25",
    photo_count: 38,
    like_count: 1045,
    view_count: 8940,
    thumbnail: null,
  },
  {
    id: 81,
    title: "Первый рабочий день нового кассира",
    description:
      "Новый сотрудник приступил к работе. Команда встретила его тепло.",
    category: "other",
    date: "2025-06-20",
    photo_count: 6,
    like_count: 41,
    view_count: 240,
    thumbnail: null,
  },
  {
    id: 82,
    title: "Мини-зоопарк на выходных",
    description:
      "Передвижной мини-зоопарк с кроликами, козами и попугаями. Дети в восторге.",
    category: "events",
    date: "2025-06-14",
    photo_count: 75,
    like_count: 567,
    view_count: 3980,
    thumbnail: null,
  },
  {
    id: 83,
    title: "Ивановы — 25 лет вместе в парке",
    description:
      "Пара отметила серебряную свадьбу там, где познакомились — в нашем парке.",
    category: "guests",
    date: "2025-06-08",
    photo_count: 20,
    like_count: 673,
    view_count: 4830,
    thumbnail: null,
  },
  {
    id: 84,
    title: "Праздник мыльных пузырей",
    description:
      "Тысячи мыльных пузырей наполнили парк. Дети и взрослые прыгали от счастья.",
    category: "events",
    date: "2025-06-01",
    photo_count: 89,
    like_count: 754,
    view_count: 5370,
    thumbnail: null,
  },
  {
    id: 85,
    title: "Утренняя тишина — будний день",
    description:
      "Парк до открытия. Серия атмосферных кадров в 6 утра без единого посетителя.",
    category: "nature",
    date: "2025-05-27",
    photo_count: 22,
    like_count: 311,
    view_count: 2240,
    thumbnail: null,
  },
  {
    id: 86,
    title: "Инспекция по безопасности",
    description:
      "Ежегодная государственная проверка всех аттракционов. Все прошли сертификацию.",
    category: "other",
    date: "2025-05-20",
    photo_count: 10,
    like_count: 73,
    view_count: 460,
    thumbnail: null,
  },
  {
    id: 87,
    title: "Открытие нового туалетного комплекса",
    description:
      "Современный санитарный комплекс открылся в центре парка. Бесконтактные краны.",
    category: "other",
    date: "2025-05-14",
    photo_count: 5,
    like_count: 38,
    view_count: 210,
    thumbnail: null,
  },
  {
    id: 88,
    title: "Цветение сакуры — аллея №3",
    description:
      "Японские сакуры расцвели раньше прогноза. Фотографы занимали очередь с рассвета.",
    category: "nature",
    date: "2025-05-08",
    photo_count: 94,
    like_count: 812,
    view_count: 6450,
    thumbnail: null,
  },
  {
    id: 89,
    title: "Экскурсия для людей с ОВЗ",
    description:
      "Инклюзивный день: аттракционы адаптированы для гостей с ограниченными возможностями.",
    category: "guests",
    date: "2025-05-03",
    photo_count: 31,
    like_count: 498,
    view_count: 3560,
    thumbnail: null,
  },
  {
    id: 90,
    title: "Парковый марафон матерей",
    description:
      "Бег с колясками — 200 мам пробежали круг почёта в день матери.",
    category: "events",
    date: "2025-04-27",
    photo_count: 57,
    like_count: 621,
    view_count: 4390,
    thumbnail: null,
  },
  {
    id: 91,
    title: "Первые ласточки вернулись",
    description: "Сезонные птицы вернулись в гнёзда под крышей кафе у пруда.",
    category: "nature",
    date: "2025-04-20",
    photo_count: 13,
    like_count: 234,
    view_count: 1670,
    thumbnail: null,
  },
  {
    id: 92,
    title: "Конкурс костюмов на Хэллоуин",
    description:
      "100 участников в костюмах соревновались за главный приз — сезонный абонемент.",
    category: "events",
    date: "2025-04-14",
    photo_count: 76,
    like_count: 543,
    view_count: 3810,
    thumbnail: null,
  },
  {
    id: 93,
    title: "Детский лагерь на каникулах",
    description:
      "Весенние каникулы: дневной лагерь для 80 детей 7–12 лет в парке.",
    category: "guests",
    date: "2025-04-07",
    photo_count: 48,
    like_count: 356,
    view_count: 2490,
    thumbnail: null,
  },
  {
    id: 94,
    title: "Уборка после шторма",
    description:
      "Сильный ветер повалил 3 дерева. Бригада устранила последствия за 4 часа.",
    category: "other",
    date: "2025-04-01",
    photo_count: 18,
    like_count: 157,
    view_count: 990,
    thumbnail: null,
  },
  {
    id: 95,
    title: "Флэшмоб «Танцы в парке»",
    description:
      "Спонтанный флэшмоб: 300 человек танцевали на центральной площади парка.",
    category: "events",
    date: "2025-03-25",
    photo_count: 65,
    like_count: 782,
    view_count: 5620,
    thumbnail: null,
  },
  {
    id: 96,
    title: "Презентация плана парка на 2025",
    description:
      "Директор представил план развития: новые аттракционы и расширение парка.",
    category: "other",
    date: "2025-03-18",
    photo_count: 14,
    like_count: 119,
    view_count: 780,
    thumbnail: null,
  },
  {
    id: 97,
    title: "Детский пасхальный квест",
    description:
      "Охота за пасхальными яйцами по всему парку. 350 детей нашли подарки.",
    category: "events",
    date: "2025-03-12",
    photo_count: 82,
    like_count: 596,
    view_count: 4170,
    thumbnail: null,
  },
  {
    id: 98,
    title: "Первые посетители весны",
    description:
      "Парк открылся после зимы. Первые 50 гостей получили цветы от администрации.",
    category: "guests",
    date: "2025-03-05",
    photo_count: 40,
    like_count: 318,
    view_count: 2230,
    thumbnail: null,
  },
  {
    id: 99,
    title: "Зимний закат над аттракционами",
    description:
      "Фотосерия заката в январе. Морозный воздух и розовое небо над каруселями.",
    category: "nature",
    date: "2025-02-15",
    photo_count: 29,
    like_count: 387,
    view_count: 2750,
    thumbnail: null,
  },
  {
    id: 100,
    title: "Новый год 2025 — первые минуты",
    description:
      "Ровно в полночь — фейерверк, шампанское и слёзы радости у фонтана.",
    category: "events",
    date: "2025-01-01",
    photo_count: 120,
    like_count: 1138,
    view_count: 9210,
    thumbnail: null,
  },
];

export const getMemories = async (): Promise<MemoryItem[]> => {
  await delay();
  return [...mockMemories].sort((a, b) => b.date.localeCompare(a.date));
};

export const createMemory = async (
  payload: CreateMemoryPayload,
): Promise<MemoryItem> => {
  await delay(600);
  const item: MemoryItem = {
    id: nextId(),
    title: payload.title,
    description: payload.description,
    category: payload.category,
    date: payload.date,
    photo_count: payload.photo_count,
    like_count: 0,
    view_count: 0,
    thumbnail: payload.thumbnail
      ? URL.createObjectURL(payload.thumbnail)
      : null,
  };
  mockMemories.unshift(item);
  return item;
};

export const updateMemory = async (
  id: number,
  payload: UpdateMemoryPayload,
): Promise<MemoryItem> => {
  await delay(500);
  const idx = mockMemories.findIndex((m) => m.id === id);
  if (idx === -1) throw new Error("Memory not found");
  const updated: MemoryItem = {
    ...mockMemories[idx],
    ...(payload.title !== undefined && { title: payload.title }),
    ...(payload.description !== undefined && {
      description: payload.description,
    }),
    ...(payload.category !== undefined && { category: payload.category }),
    ...(payload.date !== undefined && { date: payload.date }),
    ...(payload.photo_count !== undefined && {
      photo_count: payload.photo_count,
    }),
    ...(payload.thumbnail !== undefined && {
      thumbnail: payload.thumbnail
        ? URL.createObjectURL(payload.thumbnail)
        : mockMemories[idx].thumbnail,
    }),
  };
  mockMemories[idx] = updated;
  return updated;
};

export const deleteMemory = async (id: number): Promise<void> => {
  await delay(400);
  mockMemories = mockMemories.filter((m) => m.id !== id);
};
